export const conditions = [
	"Malaria",
	"Pneumonia",
	"Urinary Tract Infection",
	"Upper Respiratory Tract Infection",
	"Coryza",
	"Bronchitis",
	"Bronchiolitis",
	"Tuberculosis",
	"C.O.P.D",
	"Sinusitis",
	"Laryngitis",
	"Gonorrhea",
	"Human Papilomavirus (HPV)",
	"Bacterial Vaginosis",
	"Chlamydia",
	"Trichomoniasis",
	"Influenza",
	"Tonsillitis",
	"Gastritis",
	"Gastroenteritis",
].sort();
