export const ADDO_MEDICATIONS: string[] = [
	// "Diazepam",
	"ALU - Artemether/ lumefantrine",
	"Nasal decongestant",
	"NSAIDS - Nonsteroidal anti-inflammatory drugs",
	"ORS - Oral rehydration salts",
	"Albendazole",
	"Deworming tablets",
	"Gentamycin eyedrops",
	"Condoms",
	"Birth Control",
	// "Ampiclox",
	"Cotrimoxazole",
	"Vitamin Supplements",
	"Zinc",
	"Iron Supplements",
	"Scaboma",
	"Fluconazole",
	"Corticosteroids",
	"Folic acid tabs",
	// "Cloxacillin",
	// "Erythromycin",
	// "Cetrizine",
	"Antihistamines",
	"Hydrocortisone cream",
	"Nyastatin oral suspension",
	"Anti-fungal pessaries",
	// "Salicylic acid ointment",
	"Amoxicillin",
	// "Azithromycin",
	"Amoxicillin/Clavulanate",
	// "Clindamycin",
	// "Cephalexin",
	"Ciprofloxacin",
	"Metronidazole",
	// "Levofloxacin",
	"Doxycycline",
	"Sulfadoxine–pyrimethamine",
	"Diuretics",
	"Paracetamol",
	"Acetaminophen",
	"Ibuprofen",
	"Cough Syrup",
].sort();

const others = ["Other Antibiotics", "Other Antifungals", "Other"];

const MEDICATIONS = [...ADDO_MEDICATIONS, ...others];

export { MEDICATIONS };
