export const symptoms = [
	"dysuria",
	"frequent micturation",
	"pelvic pain",
	"back pain",
	"nausea",
	"vomiting",
	"fever",
	"fatigue",
	"genital warts",
	"vaginal itching",
	"white vaginal discharge",
	"vaginal discharge",
	"fishy vaginal discharge",
	"genital discharge",
	"abdominal pain",
	"painful scrotal swelling",
	"dyspareunia",
	"penis opening discomfort",
	"menorrhagia",
	"metrorrhagia",
	"testicular pain",
	"testicular swelling",
	"foul vaginal discharge",
	"postcoital bleeding",
	"yellow vaginal discharge",
	"penile discharge",
	"genital itching",
	"malaise",
	"headache",
	"stiff neck",
	"photophobia",
	"coma",
	"cough",
	"dyspnoea",
	"skin rash",
	"visual impairment",
	"hearing impairment",
	"lethargy",
	"confusion",
	"altered mental status",
	"focal neurological deficit",
	"diastolic hypertension",
	"low grade fever",
	"weight loss",
	"loss of consiousness",
	"paralysis",
	"motor paralysis",
	"cranial nerve palsy",
	"abnormal posturing",
	"history of tb",
	"seizures",
	"dry cough",
	"eye pain",
	"blurred vision",
	"dark urine",
	"clay coloured stools",
	"jaundice",
	"msm",
	"multiple sexual partners",
	"chills",
	"chest pain",
	"tachypnoea",
	"hypoxia after exertion",
	"productive cough",
	"night sweats",
	"burning epigastric pain",
	"epigastric pain before meals",
	"epigastric pain after meals",
	"diarrhoea",
	"sore throat",
	"rhinorrhea",
	"irritability",
	"dehydration",
	"abdominal tenderness",
	"high grade fever",
	"convulsions",
	"hypoglycemia",
	"anaemia",
	"sneezing",
	"myalgia",
	"loss of appetite",
	"loss of smell",
	"difficulty swallowing",
	"hoarseness",
	"halitosis",
	"swollen lymph nodes",
	"white patches on tonsils",
	"voice loss",
	"tender anterior neck",
	"nasal congestion",
].sort();
