name: build
on:
  push:
    branches:
      - main
      - dev
      - test/**
  pull_request:
    branches:
      - main
      - dev
      - test/**
  
jobs:
  test:
    name: Build on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12.x', '14.x']
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setting up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependecies
        run: yarn install

      - name: Build
        run: yarn android
