name: CI
on:
  push:
    branches:
      - main
      - dev
      - test/**
  pull_request:
    branches:
      - main
      - dev
      - test/**
  
jobs:
  test:
    name: Test + Code Coverage on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12.x', '14.x']
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setting up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Setting up Java Version 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Test React Native Code
        run: npm run test --ci --coverage --maxWorkers=2

      - uses: eskatos/gradle-command-action@v1
        env:
          CI: true
        with:
          build-root-directory: ./android
          gradle-version: 5.5
          arguments: build --dry-run # just test build configuration

      - name: Test Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-${{ matrix.os }}-${{ matrix.node }}
          parallel: true

          
  finish:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12.x', '14.x']
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true

